<a href="https://colab.research.google.com/github/satish32689/FDS-foundation-of-datascience/blob/main/numpy_practical0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)

1.23.5


In [ ]:
"""Write a NumPy program to test whether none of the
elements of a given array are zero.
"""

import numpy as np
s=np.array([1,2,3,4,5])

print("original array:",s)
print("test if non of the elements of the said array is 0:")
print(np.all(s))

s=np.array([0,1,2,3,4,5])

print("original array:",s)
print("test if non of the elements of the said array is 0:")
print(np.all(s))


original array: [1 2 3 4 5]
test if non of the elements of the said array is 0:
True
original array: [0 1 2 3 4 5]
test if non of the elements of the said array is 0:
False


In [ ]:
"""Write a NumPy program to create an element-wise
comparison (greater, greater_equal, less and less_equal) of
two given arrays."""

import numpy as np
s=np.array([2,3,6])
p=np.array([1,4,6])

print("original number :",s,p)
print("---------------")
print("comparison-grater between s to p",np.greater(s,p))
print("comparison-grater between p to s",np.greater(p,s))
print("---------------")
print("comparison- greater equal between s to p",np.greater_equal(s,p))
print("comparison- greater equal between p to s",np.greater_equal(p,s))
print("---------------")
print("comparison-grater between s to p",np.less(s,p))
print("comparison-grater between p to s",np.less(p,s))
print("---------------")
print("comparison- greater equal between s to p",np.less_equal(s,p))
print("comparison- greater equal between p to s",np.less_equal(p,s))


original number : [2 3 6] [1 4 6]
---------------
comparison-grater between s to p [ True False False]
comparison-grater between p to s [False  True False]
---------------
comparison- greater equal between s to p [ True False  True]
comparison- greater equal between p to s [False  True  True]
---------------
comparison-grater between s to p [False  True False]
comparison-grater between p to s [ True False False]
---------------
comparison- greater equal between s to p [False  True  True]
comparison- greater equal between p to s [ True False  True]


In [ ]:
"""Write a NumPy program to create an array with the values
1, 7, 13, 105 and determine the size of the memory occupied
by the array."""

import numpy as np

b=np.array([1,7,12,105])
c=np.array([2,6,852])
print("original arry:",b,c)
print("---------------")

print("Size of the memory occupied by the said array:")
print("%d bytes" % (b.size*b.itemsize))
print("%d bytes" % (c.size*c.itemsize))


original arry: [  1   7  12 105] [  2   6 852]
---------------
Size of the memory occupied by the said array:
32 bytes
24 bytes


In [ ]:
"""Write a NumPy program to create an array of integers
from 30 to 70."""

import numpy as np
r=np.arange(30, 71)
print("array of the integers from 30 to 70",r)


array of the integers from 30 to 70 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
"""Write a NumPy program to create an array of all even
integers from 30 to 70."""

import numpy as np
t=np.arange(30,71,2)
print("array of all the even integers from 30 to 70",t)

array of all the even integers from 30 to 70 [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [ ]:
#odd number

import numpy as np
t=np.arange(30+(30+1)%2,71,2)
print("array of all the odd integers from 30 to 70",t)

array of all the odd integers from 30 to 70 [31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69]


In [ ]:
"""Write a NumPy program to create a 3x3 identity matrix."""

import numpy as n
y2d=n.identity(3)

print('3x3 matrix:',y2d)

3x3 matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
"""Write a search NumPy program to create a 3X4 array and
iterate over it."""

import numpy as n
g=n.arange(10,22).reshape((3,4))

print('original array:',g)
print('Each element of the array is:')
for c in n.nditer(g):
  print(c, end=" ")

original array: [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

In [ ]:
import numpy as n
g=n.arange(20,36).reshape((4,4))

print('original array:',g)
print('Each element of the array is:')
for c in n.nditer(g):
  print(c, end=" ")

original array: [[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]
Each element of the array is:
20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 